"use client";
import { FormEvent, useEffect, useState } from "react";
import { defaultContent, type SiteContent } from "../../lib/site-types";
const initial = { parentName: "", phone: "", childName: "", childAge: "", packageName: "", city: "", message: "" };
export default function OrderPage() {
 const [content,setContent]=useState<SiteContent>(defaultContent); const [form,setForm]=useState(initial); const [message,setMessage]=useState("");
 useEffect(()=>{ const selected=new URLSearchParams(window.location.search).get("package"); fetch("/api/content").then(r=>r.json()).then((data:SiteContent)=>{setContent(data); setForm(old=>({...old,packageName:selected || old.packageName || data.packages[0]?.name || ""}));});},[]);
 async function submit(e:FormEvent){e.preventDefault();setMessage("در حال ثبت سفارش...");const res=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});if(res.ok) location.href=`/payment-success?package=${encodeURIComponent(form.packageName)}`;else setMessage("ثبت سفارش انجام نشد؛ لطفاً دوباره تلاش کنید.");}
 return <main className="orderPage" dir="rtl"><a className="back" href="/">← بازگشت به سایت</a><section className="orderBox"><small>آکادمی زبان میرلو</small><h1>ثبت درخواست پکیج آموزشی</h1><p>اطلاعات زیر فقط برای هماهنگی و انتخاب پکیج مناسب استفاده می‌شود.</p><form onSubmit={submit}><label>نام و نام خانوادگی والد<input required value={form.parentName} onChange={e=>setForm({...form,parentName:e.target.value})}/></label><label>شماره تماس<input required inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>نام کودک<input required value={form.childName} onChange={e=>setForm({...form,childName:e.target.value})}/></label><label>سن کودک<input required placeholder="مثلاً ۵ سال" value={form.childAge} onChange={e=>setForm({...form,childAge:e.target.value})}/></label><label>پکیج موردنظر<select required value={form.packageName} onChange={e=>setForm({...form,packageName:e.target.value})}>{content.packages.map(item=><option key={item.name}>{item.name}</option>)}</select></label><label>شهر<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label className="wide">توضیحات یا سوال شما<textarea value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label><button>ثبت درخواست</button></form>{message&&<p className="orderMessage">{message}</p>}</section></main>;
}
